language: elixir
cache:
  directories:
  - deps
  - _build
addons:
  postgresql: "9.5"

elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.0

otp_release:
  - 18.3
  - 19.3
  - 20.2

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.2
    - elixir: 1.6.0
      otp_release: 18.3

env:
  global:
    - MIX_ENV=test
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
  # Run static code analysis
  - "mix credo"
  # Check code style
  - "mix dogma"

